name: dagger-build

on: [ 'push', 'pull_request', 'workflow_dispatch' ]

env:
  COVERALLS_GIT_COMMIT: '${{ github.sha }}'
  COVERALLS_GIT_BRANCH: '${{ github.ref.name }}'
  COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dagger
        run: 'cd /usr/local && curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.2.36 sh'
      
      - name: Dagger project update
        run: 'dagger project update'
      
      - name: Run build
        run: 'dagger do build'
